# -*- coding: utf-8 -*-
"""EASY ADS TRACKER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nf-hE8RkZPN4G_T7zp41cReCZj6T-Yiu
"""

!pip install gspread oauth2client

import gspread
import pandas as pd
from pprint import pprint
from oauth2client.service_account import ServiceAccountCredentials
scope = ["https://spreadsheets.google.com/feeds",
         'https://www.googleapis.com/auth/spreadsheets',
         "https://www.googleapis.com/auth/drive.file",
         "https://www.googleapis.com/auth/drive"]
creds = ServiceAccountCredentials.from_json_keyfile_name("/content/creds.json", scope)
client = gspread.authorize(creds)
sheet=client.open("ads").sheet1

data=sheet.get_all_records()
df = pd.DataFrame(sheet.get_all_records())
import pandas as pd
#_______________________________________________________________________________

#These are strings to make the needed function in GoogleSheet. (It was the easiest way to me even if it's look complicated.)
my_string="=GOOGLEFINANCE({},{},{})"
my_string2="=GOOGLEFINANCE({},{})"
t='""'
#____________________________________________________________________

#These variables will be used later. (Historical price, Date, and a list to fill with both values.)
fecha_precio=0
fecha_compra=0
lista_historial=[]


#this function is for filling the next available rows automatically 
def next_available_row(sheet):
    str_list = list(filter(None, sheet.col_values(1)))
    return str(len(str_list)+1)

next_row = next_available_row(sheet)

next_available_row(sheet)


#___________________________________________________________________
#FUNCTION TO CLEAN VALUES OF GOOGLE SHEET AFTER REACHING CELL D50

def clean_values(*args):
  cell_list = sheet.range("C1:D50")
  sheet.update_acell("D51",'=ISBLANK(D50)')  
  for cell in cell_list:
    cell.value = ''
  sheet.update_cells(cell_list)

#This is basically a function to make a watchlist of stocks(redundant I know)
#These tickers are for CEDEARS (ARGENTINIAN ADS)

def watchlist(*args):
  symbol_list=[]
  while True:
    symbol=input("Ingrese los tickers: ")
    if symbol=="salir":
      break 
    symbol_list.append(symbol.upper())
  for i in range(len(symbol_list)): 
    if symbol_list[i] in df.values:
      df2=df.loc[df['ticker'] == symbol_list[i]] #LOOPING THROUGH LIST TO PRINT THE REQUIRED SYMBOLS AND IT'S PRICES
      print(df2)
  val=sheet.acell("D51")
  if val.value=='FALSE':
    clean_values()  
  
  
def rendimiento_compra(): #function to watch your performance in the stocks. 
  global ticker
  ticker=input("Ingrese ticker en formato cedear (ejemplo 'BCBA:AAPL'): ")
  ticker_final=t[:1]+ticker+t[1:] #This is to make the ticker symbol being between Quotation marks
  fecha=input("Ingrese fecha de compra en formato AÑO/MES/DIA : ")
  fecha_final=t[:1]+fecha+t[1:]
  n=float(input("Ingrese la cantidad de acciones compradas: "))

  #___________________________________________________________________________________
  funcion2=my_string2.format(ticker_final,'"price"')
  funcion=my_string.format(ticker_final,'"price"',fecha_final)
  sheet.update_acell("C{}".format(next_row), funcion2)
  precio_actual=sheet.acell("C{}".format(next_row)).value
  sheet.update_acell("D1",funcion)
  #All of these formating functions above are to make the Spreadsheet functions work.
  
  #Accesing to the values.
  fecha_compra=sheet.acell('D2').value
  lista_historial.append(fecha_compra)
  fecha_precio=sheet.acell('E2').value
  lista_historial.append(fecha_precio)
  lista_historial.append(ticker)
  precio_actual2=precio_actual.strip("$")
  
  #Calculating the performances
  rendimiento=(float(precio_actual2)-float(fecha_precio))
  print("Su ganancia/pérdida es de: $", (float(rendimiento))*(n))
  print("porcentage de ganancia/pérdida es de", float(rendimiento*100)/float(fecha_precio), "%")

#rendimiento_compra()
watchlist()